package com.example.axiom.ui.screens.finances.product.constants

val GST_UNITS = listOf(
    "BAG" to "Bag",
    "BAL" to "Bale",
    "BDL" to "Bundle",
    "BKL" to "Buckles",
    "BOU" to "Billions of Units",
    "BOX" to "Box",
    "BTL" to "Bottle",
    "BUN" to "Bunch",
    "CAN" to "Can",
    "CBM" to "Cubic Meter",
    "CCM" to "Cubic Centimeter",
    "CMS" to "Centimeter",
    "CTN" to "Carton",
    "DOZ" to "Dozen",
    "DRM" to "Drum",
    "GGR" to "Great Gross",
    "GMS" to "Gram",
    "GRS" to "Gross",
    "GYD" to "Gross Yard",
    "KGS" to "Kilogram",
    "KLR" to "Kilolitre",
    "KME" to "Kilometre",
    "MLT" to "Millilitre",
    "MTR" to "Metre",
    "MTS" to "Metric Tonne",
    "NOS" to "Number",
    "PAC" to "Pack",
    "PCS" to "Piece",
    "PRS" to "Pair",
    "QTL" to "Quintal",
    "ROL" to "Roll",
    "SET" to "Set",
    "SQF" to "Square Foot",
    "SQM" to "Square Metre",
    "SQY" to "Square Yard",
    "TBS" to "Tablets",
    "TGM" to "Ten Gross",
    "THD" to "Thousand",
    "TON" to "Tonne",
    "TUB" to "Tube",
    "UGS" to "US Gallon",
    "UNT" to "Unit",
    "YDS" to "Yard",
    "OTH" to "Other"
)